pipeline_name: complex_pipeline
project_name: example_project
description: "A complex pipeline with multiple interdependent steps"
steps:
  - name: step1
    class_name: example_project.steps.step1.Step1
    depends: []

  - name: step2
    class_name: example_project.steps.step2.Step2
    depends: [step1]

  - name: step3
    class_name: example_project.steps.step3.Step3
    depends: [step1]

  - name: step4
    class_name: example_project.steps.step4.Step4
    depends: [step2, step3]

  - name: step5
    class_name: example_project.steps.step5.Step5
    depends: [step2]

  - name: step6
    class_name: example_project.steps.step6.Step6
    depends: [step4]

  - name: step7
    class_name: example_project.steps.step7.Step7
    depends: [step4]

  - name: step8
    class_name: example_project.steps.step8.Step8
    depends: [step5, step6]

  - name: step9
    class_name: example_project.steps.step9.Step9
    depends: [step7]

  - name: step10
    class_name: example_project.steps.step10.Step10
    depends: [step8, step9]
  

